### PR TITLE
add contact types

### PR DESCRIPTION
**Pull request by bdevloed**
contact points as secondary when:
- There is NO address linked to the contactpoint AND another contact point for the mandataris exists.

Label all other contactpoints as primary. i.e. 
- only contact point (with or without address)
- OR the contact point with an address in case of multiple contact points per mandataris.

fyi, there are no cases of more than one contactpoint per mandataris with an address.

### CODE REVIEW

**Comment by Windvis** [comment]
Sounds good. I'm not the best to review the SPARQL query itself though. 

Should we wait to merge this until the frontend code uses the same logic? Otherwise we might have to run the migration again in the future?

**Comment by bdevloed** [comment]
It can be done before I think. This migration only adds information which isn't used yet. No existing triples are deleted or modified. 
But let me know if I miss something.

**Comment by Windvis** [comment]
Maybe I'm the one misunderstanding. What I believe this does is properly "label" the contact points. So instead of depending on the order in the database (and assume the first one is primary) we can use the `Primary` and `Secondary` labels instead?

If we run this migration now it will update the database to this new system, but the frontend will still create new contact points without these labels. So unless we also implement the frontend changes before merging I think there will be a period were "wrong" data can be inserted into the DB? So we would have to run this a second time when the actual frontend work is done?

**Comment by bdevloed** [comment]
@Windvis  ah yes indeed. Will put it in draft in the meantime to avoid an accidental merge.

**Pull request merged**
